/// STL Includes
#include <iostream>
#include <fstream>

/// ANTLR Includes
#include "antlr4-runtime.h"

/// Autogenerated Includes
#include "CLexer.h"
#include "CParser.h"
#include "CBaseListener.h"

/// ANLTR namespace
using namespace antlr4;



class Listener : public CBaseListener
{
public:

    void enterPrimaryExpression(CParser::PrimaryExpressionContext * ctx) override
    {

    }
};

static void token_dump(CommonTokenStream & token_stream)
{
    std::ofstream ofile("token_dump.txt");

    std::cout << "Tokens:" << std::endl;
    ofile     << "Tokens:" << std::endl;

    token_stream.fill();

    for (auto & token : token_stream.getTokens())
    {
        std::cout << token->getText() << std::endl;
        ofile     << token->getText() << std::endl;
    }
}

/// MAIN
int main(int argc, const char* argv[])
{
    if (argc < 2)
    {
        throw "Missing required argument : source file";
    }

    std::ifstream     stream(argv[1]);  ///< Open STDIN stream for input source file

    ANTLRInputStream  input(stream);    ///< ANTLR scanner / parser stream using above source file

    CLexer            lexer(&input);    ///< Lexer

    CommonTokenStream tokens(&lexer);   ///< Feed lexer into token stream
    
    CParser           parser(&tokens);  ///< Parser
    
    Listener          listener;         ///< IDK

    token_dump(tokens);

    return 0;
}
